service: teste
frameworkVersion: "2"
provider:
  name: aws
  region: us-east-1
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  deploymentBucket:
    name: ${self:service}-deployment-bucket
    serverSideEncryption: AES256
functions:
  hello:
    handler: src/modules/handler.hello
plugins:
  - serverless-localstack
  - serverless-deployment-bucket
custom:
  localstack:
    debug: true
    stages:
      - local
      - dev
    endpointFile: localstack_endpoints.json
